### ISSUE TITLE
Stuttering Video in apps using WebKit

### ISSUE THREAD

**Issue by yarbsemaj** [elementary/debian-template#4]
Video stutters, in both chrome and Skype, including my stream in Skype. Moving mouse fixes issue and does disabling hardware acceleration on chrome. Seems to be a long standing issue based on comments on Reddit

Graphics intel GMA 620

**Comment by HansCronau** [comment]
Could this be a double of https://github.com/elementary/os/issues/121 posted on the wrong project?
